### ISSUE TITLE
Incorrectly generated description

### ISSUE THREAD

**Issue by jbrooksuk** [crescat-io/saloon-sdk-generator#2]
Given this API: https://developers.checkmango.com/operation/operation-createexperiment

The generated request class `CreateExperiment` has a bad comment:

```diff
/**
 * createExperiment
 */
class CreateExperiment extends Request
{
	protected Method $method = Method::POST;


	public function resolveEndpoint(): string
	{
		return "/api/teams/{$this->team}/experiments";
	}


	/**
-	 * @param int $team The ID of the team to list experiments in.
+	 * @param int $team The ID of the team to create the experiment in.
	 */
	public function __construct(
		protected int $team,
	) {
	}
}

```

**Comment by HelgeSverre** [comment]
This is due to the OpenAPI Parameter description being defined on the "paths" instead of on the individual endpoints in the openapi spec:

![image](https://github.com/crescat-io/saloon-sdk-generator/assets/1089652/18dcb605-aac0-4d5b-9bd8-d14c2ff19486)


```json
{
  "get": {
    // ... 
  },
  "post": {
    // ...
  },
  "parameters": [
    {
      "in": "path",
      "name": "team",
      "description": "The ID of the team to list experiments in.", // Defined here
      "example": 3,
      "required": true,
      "schema": {
        "type": "integer"
      }
    }
  ]
}
```

If you move the parameter definition inside the get/post and give them individual descriptions, this should work as expected.

**Comment by HelgeSverre** [comment]
Closing this, as its not a package bug, let me know if i have misunderstood.
